In [3]:
# Numpy
# Fundamental library help to computing

In [4]:
import numpy as np

## create arrays using numpy
arr_1D=np.array([1,2,3,4,5,6])
print(arr_1D)
print(arr_1D.shape)

[1 2 3 4 5 6]
(6,)


In [10]:
arr_2D=np.array([1,2,3,4,5])
arr_2D.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [12]:
## Identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
## Vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## element wise addition
print(arr1+arr2) ## Output: [11 22 33 44 55]


## element wise substractions
print(arr1-arr2) ## [ -9 -18 -27 -36 -45]

## element wise multiply
print(arr1*arr2) ## output : [ 10  40  90 160 250]

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]


In [20]:
## Universal function
arr=np.array([2,3,4,5,6])

## squaroot
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [27]:
## Arrays slicing and indexing

array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array[0][2])

3


In [29]:
### Statical concepts : Normalization
## to have mean of 0 and std daviation of 1

data=np.array([2,3,4,5,6])


## Mean calculation
mean=np.mean(data)

##calculating Standard deviation
std_dev=np.std(data)

normalizedData=(data-mean)/std_dev

## variance
var=np.var(data)


In [32]:
## Logical operations

data[data>5]

array([6])